import { createPCB } from '../types/process';

export const PRESETS = [
  {
    id: 'multitasking',
    name: 'Standard OS Multitasking Mix',
    description: 'Mix of CPU and I/O processes with varied priorities and staggered arrival times.',
    algorithm: 'RR',
    timeQuantum: 3,
    processes: [
      createPCB({
        pid: 1,
        name: 'Web Browser',
        priority: 2,
        totalBurst: 10,
        arrivalTime: 0,
        memoryMB: 128,
        ioEvents: [{ triggerAt: 3, device: 'Network', duration: 2 }],
      }),
      createPCB({
        pid: 2,
        name: 'Code Editor',
        priority: 1,
        totalBurst: 7,
        arrivalTime: 1,
        memoryMB: 64,
        ioEvents: [{ triggerAt: 4, device: 'Disk', duration: 2 }],
      }),
      createPCB({
        pid: 3,
        name: 'Music Player',
        priority: 3,
        totalBurst: 8,
        arrivalTime: 2,
        memoryMB: 48,
        ioEvents: [{ triggerAt: 2, device: 'Disk', duration: 3 }],
      }),
      createPCB({
        pid: 4,
        name: 'DB Sync Worker',
        priority: 2,
        totalBurst: 12,
        arrivalTime: 3,
        memoryMB: 256,
        ioEvents: [{ triggerAt: 4, device: 'Network', duration: 3 }],
      }),
    ],
  },
  {
    id: 'staggered_srtf',
    name: 'Staggered Arrival (SJF / SRTF Demo)',
    description: 'Processes arriving at T=0, T=2, T=4 demonstrating preemption of long jobs by short jobs.',
    algorithm: 'SRTF',
    timeQuantum: 2,
    processes: [
      createPCB({
        pid: 1,
        name: 'Long Task P1',
        priority: 3,
        totalBurst: 12,
        arrivalTime: 0,
        memoryMB: 64,
      }),
      createPCB({
        pid: 2,
        name: 'Medium Task P2',
        priority: 2,
        totalBurst: 5,
        arrivalTime: 2,
        memoryMB: 32,
      }),
      createPCB({
        pid: 3,
        name: 'Quick Task P3',
        priority: 1,
        totalBurst: 2,
        arrivalTime: 4,
        memoryMB: 16,
      }),
    ],
  },
  {
    id: 'round_robin_race',
    name: 'Round Robin Quantum Slicing',
    description: 'Equal length CPU-bound tasks competing in round-robin turns with time quantum slices.',
    algorithm: 'RR',
    timeQuantum: 2,
    processes: [
      createPCB({ pid: 1, name: 'Ray Tracer P1', priority: 2, totalBurst: 8, arrivalTime: 0, memoryMB: 64 }),
      createPCB({ pid: 2, name: 'Video Render P2', priority: 2, totalBurst: 8, arrivalTime: 0, memoryMB: 96 }),
      createPCB({ pid: 3, name: 'Crypto Hash P3', priority: 2, totalBurst: 8, arrivalTime: 0, memoryMB: 32 }),
    ],
  },
  {
    id: 'priority_preemption',
    name: 'Preemptive Priority Scheduling',
    description: 'High-priority real-time processes preempting background low-priority indexers.',
    algorithm: 'PRIORITY_PREEMPTIVE',
    timeQuantum: 3,
    processes: [
      createPCB({ pid: 1, name: 'Background Indexer', priority: 4, totalBurst: 14, arrivalTime: 0, memoryMB: 32 }),
      createPCB({ pid: 2, name: 'Compiler Service', priority: 3, totalBurst: 8, arrivalTime: 2, memoryMB: 128 }),
      createPCB({ pid: 3, name: 'Realtime UI Dispatch', priority: 1, totalBurst: 4, arrivalTime: 4, memoryMB: 48 }),
      createPCB({ pid: 4, name: 'Kernel Watchdog', priority: 1, totalBurst: 3, arrivalTime: 6, memoryMB: 16 }),
    ],
  },
  {
    id: 'io_heavy',
    name: 'I/O Device Bottleneck & Queue Cycling',
    description: 'Multiple processes performing heavy Disk and Network operations with frequent context switches.',
    algorithm: 'FCFS',
    timeQuantum: 3,
    processes: [
      createPCB({
        pid: 1,
        name: 'File Downloader',
        priority: 2,
        totalBurst: 9,
        arrivalTime: 0,
        memoryMB: 64,
        ioEvents: [
          { triggerAt: 2, device: 'Network', duration: 4 },
          { triggerAt: 6, device: 'Disk', duration: 2 },
        ],
      }),
      createPCB({
        pid: 2,
        name: 'Disk Defragmenter',
        priority: 3,
        totalBurst: 10,
        arrivalTime: 1,
        memoryMB: 128,
        ioEvents: [{ triggerAt: 3, device: 'Disk', duration: 3 }],
      }),
      createPCB({
        pid: 3,
        name: 'Keyboard Listener',
        priority: 1,
        totalBurst: 6,
        arrivalTime: 2,
        memoryMB: 16,
        ioEvents: [{ triggerAt: 2, device: 'Keyboard', duration: 2 }],
      }),
    ],
  },
];
